### ISSUE TITLE
Allow the reporter to be configured in the Phantomas constructor

### ISSUE THREAD

**Issue by garrettr** [macbre/phantomas-python#8]
Phantomas supports a variety of [reporters](https://www.npmjs.com/package/phantomas#parameters) for different output formats. However, on https://github.com/macbre/phantomas-python/blob/master/phantomas/client.py#L41, phantomas-python sets the reporter to be `'json'` and overrides any reporter that is set in the kwargs to the constructor.

It would be nice to make it possible to return the CSV results directly (or have them easily accessible from the `results.Results` object), so projects that want to use one of the built-in output formats don't have to convert them from JSON/`results.Results`.

**Comment by macbre** [comment]
@garrettr, can you provide a use case of using CSV-formatted phantomas results in Python? Won't using Python's CSV writer along with `results.get_metrics()` be enough?

**Comment by garrettr** [comment]
@macbre I wasn't sure if there were differences between the JSON schema and the CSV schema. Since JSON can be nested, they don't necessarily inter-convert without some manual resolution. However, looking more at the code and the Phantomas docs, it looks like the JSON schema is just a single-level dict, so your suggested solution of using the CSV writer with `results.get_metrics()` should be sufficient. Thanks!

**Comment by macbre** [comment]
@garrettr, np :)

Closing this one.
